## default connection pool
## Changes to the Default Error Page’s Content
## The error message and any binding errors are no longer included in the default
## error page by default. This reduces the risk of leaking information to a client.
## server.error.include-message and server.error.include-binding-errors can be used
## to control the inclusion of the message and binding errors respectively.
## Supported values are always, on-param, and never.
server:
  port: 8184
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: securityservice
  jpa:
    #spring.jpa.hibernate.ddl-auto=create #drop n create table again, good for testing, comment this in production
    properties:
      hibernate:
        default_schema: secu
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://164.68.106.161:5432/prod_socec
    username: postgres
    password: P@ssw0rd21

  ## Custom data
userdata:
  timeout: 30

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/