## default connection pool
server:
  port: 8184

spring:
  application:
    name: securityservice
  jpa:
    #spring.jpa.hibernate.ddl-auto=create #drop n create table again, good for testing, comment this in production
    properties:
      hibernate:
        default_schema: secu
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://164.68.106.161:5432/dev_socec
    username: postgres
    password: P@ssw0rd21

  ## Custom data
userdata:
  timeout: 30

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/