version: '3'
services:
  pprdfinancewseurekadiscovery:
    restart: on-failure
    container_name: pprdfinancewseurekadiscovery
    build: ./financewseurekadiscovery
    ports:
      - "28761:28761"
    environment:
      server.port: '28761'

  pprdfinancewsgatewayservice:
    restart: on-failure
    container_name: pprdfinancewsgatewayservice
    build: ./financewsgatewayservice
    ports:
      - "28762:28762"
    depends_on:
      - pprdfinancewseurekadiscovery
    links:
      - pprdfinancewseurekadiscovery
    environment:
      server.port: '28762'
      eureka.client.enabled: 'true'
      eureka.host: pprdfinancewseurekadiscovery
      eureka.instance.preferIpAddress: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://pprdfinancewseurekadiscovery:28761/eureka/'
      zuul.routes.financewssecurity.url: 'http://pprdfinancewssecurityservice:28184'
      zuul.routes.financewsclient.url: 'http://pprdfinancewsclientservice:28183'
      zuul.routes.financewsfrontoffice.url: 'http://pprdfinancewsfrontofficeservice:28185'

  pprdfinancewssecurityservice:
    restart: on-failure
    container_name: pprdfinancewssecurityservice
    build: ./financewssecurityservice
    ports:
      - "28184:28184"
    depends_on:
      - pprdfinancewseurekadiscovery
    links:
      - pprdfinancewseurekadiscovery
    environment:
      server.port: '28184'
      eureka.client.enabled: 'true'
      eureka.host: pprdfinancewseurekadiscovery
      eureka.instance.preferIpAddress: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://pprdfinancewseurekadiscovery:28761/eureka/'
      spring.jpa.properties.hibernate.default_schema: secu
      spring.datasource.hikari.connectionTimeout: 20000
      spring.datasource.hikari.maximumPoolSize: 5
      spring.datasource.url: jdbc:postgresql://164.68.106.161:5432/dev_socec
      spring.datasource.username: postgres
      spring.datasource.password: P@ssw0rd21

  pprdfinancewsclientservice:
    restart: on-failure
    container_name: pprdfinancewsclientservice
    build: ./financewsclientservice
    ports:
      - "28183:28183"
    depends_on:
      - pprdfinancewseurekadiscovery
    links:
      - pprdfinancewseurekadiscovery
    environment:
      server.port: '28183'
      eureka.client.enabled: 'true'
      eureka.host: pprdfinancewseurekadiscovery
      eureka.instance.preferIpAddress: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://pprdfinancewseurekadiscovery:28761/eureka/'
      spring.jpa.properties.hibernate.default_schema: para
      spring.datasource.hikari.connectionTimeout: 20000
      spring.datasource.hikari.maximumPoolSize: 5
      spring.datasource.url: jdbc:postgresql://164.68.106.161:5432/dev_socec
      spring.datasource.username: postgres
      spring.datasource.password: P@ssw0rd21

  pprdfinancewsfrontofficeservice:
    restart: on-failure
    container_name: pprdfinancewsfrontofficeservice
    build: ./financewsfrontofficeservice
    ports:
      - "28185:28185"
    depends_on:
      - pprdfinancewseurekadiscovery
    links:
      - pprdfinancewseurekadiscovery
    environment:
      server.port: '28185'
      eureka.client.enabled: 'true'
      eureka.host: pprdfinancewseurekadiscovery
      eureka.instance.preferIpAddress: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://pprdfinancewseurekadiscovery:28761/eureka/'
      spring.jpa.properties.hibernate.default_schema: frof
      spring.datasource.hikari.connectionTimeout: 20000
      spring.datasource.hikari.maximumPoolSize: 5
      spring.datasource.url: jdbc:postgresql://164.68.106.161:5432/dev_socec
      spring.datasource.username: postgres
      spring.datasource.password: P@ssw0rd21