## default connection pool
server:
  port: 8762

spring:
  application:
    name: gatewayservice

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    financewssecurity:
      url: http://localhost:8184
    financewsclient:
      url: http://localhost:8183
    financewsfrontoffice:
      url: http://localhost:8185
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  eureka:
    enabled: false